export const messageConstants = {
    LOADING:"LOADING",
    RESPONSE_STATE:"RESPONSE_STATE",
    GET_MESSAGES:"GET_MESSAGES",
    GET_CONVERSATIONS:"GET_CONVERSATIONS",
    GET_USERS_FOR_CHAT:"GET_USERS_FOR_CHAT",
}